[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
what_transfer_hook = "HSADtk7EsvDyMo55QA9fnDZubM31D1LTRrnp36itpydJ"

[programs.devnet]
what_transfer_hook = "HSADtk7EsvDyMo55QA9fnDZubM31D1LTRrnp36itpydJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/joe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
